CREATE TABLE DOC_PESSOAS (
 NUMERO_DOCUMENTO CHAR(10),
 ORGAO_EMISSOR CHAR(10),
 VALIDADE CHAR(10),
 DT_ALTERACAO CHAR(10)
);


CREATE TABLE ENDERECOS (
 ID_ENDERECO INT NOT NULL,
 LOGRADOURO VARCHAR(255) NOT NULL,
 TELEFONE_1 VARCHAR(15) NOT NULL,
 TELEFONE_2 VARCHAR(10),
 TELEFONE_3 VARCHAR(15),
 NUMERO CHAR(10),
 COMPLEMENTO VARCHAR(255),
 BAIRRO VARCHAR(255) NOT NULL,
 MUNICIPIO VARCHAR(255),
 CEP CHAR(10),
 EMAIL VARCHAR(255),
 IND_ATIVO CHAR(1),
 DT_ALTERACAO DATE,
 ID_PESSOA INT NOT NULL
);

ALTER TABLE ENDERECOS ADD CONSTRAINT PK_ENDERECOS PRIMARY KEY (ID_ENDERECO);


CREATE TABLE PESSOAS (
 ID_PESSOA INT NOT NULL,
 NOME VARCHAR(255) NOT NULL,
 NOME_FANTASIA VARCHAR(255),
 NOME_SOCIAL VARCHAR(255),
 DT_NASCIMENTO DATE,
 OBSERVACAO VARCHAR(1024),
 CPF_CNPJ CHAR(20),
 RG_IE CHAR(20),
 DT_ALTERACAO DATE NOT NULL,
 ID_ENDERECO INT
);

ALTER TABLE PESSOAS ADD CONSTRAINT PK_PESSOAS PRIMARY KEY (ID_PESSOA);


CREATE TABLE SITUACOES_OS (
 ID_SITUACAO INT NOT NULL,
 DESCRICAO VARCHAR(255),
 IND_TECNICO CHAR(1),
 IND_FINALIZA CHAR(1)
);

ALTER TABLE SITUACOES_OS ADD CONSTRAINT PK_SITUACOES_OS PRIMARY KEY (ID_SITUACAO);


CREATE TABLE USUARIOS (
 ID_USUARIO INT NOT NULL,
 SENHA CHAR(10),
 DT_ALTERACAO DATE,
 ID_PESSOA INT NOT NULL
);

ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIO);


CREATE TABLE CLIENTES (
 ID_CLIENTE INT NOT NULL,
 TIPO_CLIENTE CHAR(10),
 DT_ALTERACAO DATE,
 ID_PESSOA INT NOT NULL
);

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE);


CREATE TABLE ORDENS_SERVICO (
 ID_ORDEM_SERVICO INT NOT NULL,
 COD_OS CHAR(10),
 MARCA VARCHAR(255),
 MODELO VARCHAR(255),
 NUM_SERIE VARCHAR(100),
 OPERADORA VARCHAR(255),
 DEFEITO VARCHAR(1024),
 LAUDO VARCHAR(1024),
 INFO_COMPLEMENTAR VARCHAR(1024),
 VALOR_SERVICO DECIMAL(10,2),
 VALOR_PECAS DECIMAL(10,2),
 DT_ENTRADA DATE,
 DT_SAIDA DATE,
 ID_USUARIO INT NOT NULL,
 ID_CLIENTE INT NOT NULL
);

ALTER TABLE ORDENS_SERVICO ADD CONSTRAINT PK_ORDENS_SERVICO PRIMARY KEY (ID_ORDEM_SERVICO);


CREATE TABLE TECNICOS (
 ID_TECNICO CHAR(10) NOT NULL,
 ID_USUARIO INT NOT NULL
);

ALTER TABLE TECNICOS ADD CONSTRAINT PK_TECNICOS PRIMARY KEY (ID_TECNICO);


CREATE TABLE ALTERACOES_OS (
 ID_ALTERACAO_OS INT NOT NULL,
 DT_ALTERACAO DATE,
 HR_ALTERACAO DATE,
 ID_USUARIO INT NOT NULL,
 ID_ORDEM_SERVICO INT NOT NULL,
 ID_SITUACAO INT NOT NULL,
 ID_TECNICO CHAR(10) NOT NULL
);

ALTER TABLE ALTERACOES_OS ADD CONSTRAINT PK_ALTERACOES_OS PRIMARY KEY (ID_ALTERACAO_OS);


ALTER TABLE ENDERECOS ADD CONSTRAINT FK_ENDERECOS_0 FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS (ID_PESSOA);


ALTER TABLE PESSOAS ADD CONSTRAINT FK_PESSOAS_0 FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECOS (ID_ENDERECO);


ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_0 FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS (ID_PESSOA);


ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES_0 FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS (ID_PESSOA);


ALTER TABLE ORDENS_SERVICO ADD CONSTRAINT FK_ORDENS_SERVICO_0 FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO);
ALTER TABLE ORDENS_SERVICO ADD CONSTRAINT FK_ORDENS_SERVICO_1 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE);


ALTER TABLE TECNICOS ADD CONSTRAINT FK_TECNICOS_0 FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO);


ALTER TABLE ALTERACOES_OS ADD CONSTRAINT FK_ALTERACOES_OS_0 FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO);
ALTER TABLE ALTERACOES_OS ADD CONSTRAINT FK_ALTERACOES_OS_1 FOREIGN KEY (ID_ORDEM_SERVICO) REFERENCES ORDENS_SERVICO (ID_ORDEM_SERVICO);
ALTER TABLE ALTERACOES_OS ADD CONSTRAINT FK_ALTERACOES_OS_2 FOREIGN KEY (ID_SITUACAO) REFERENCES SITUACOES_OS (ID_SITUACAO);
ALTER TABLE ALTERACOES_OS ADD CONSTRAINT FK_ALTERACOES_OS_3 FOREIGN KEY (ID_TECNICO) REFERENCES TECNICOS (ID_TECNICO);


